# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Something Spatial
name: Tomas Holderness
email: tomash@mit.edu
description: > # this means to ignore newlines until "baseurl:"
  Reseach Scientist - Geographer - Urban Risk Specialist
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://somethingspatial.net" # the base hostname & protocol for your site

# Social media profiles - feel free to add more here
twitter_username: iHolderness
github_username:  TallTom
#instagram_username: beyonce
#stackoverflow_url: https://
#googleplus_username: BobMarley
#skype_username: echo123
#linkedin_url: https://
# TODO
# wordpress blog

# Address information
address_street: Urban Risk Lab, Massachusetts Institute of Technology
address_city: Cambridge
address_state: MA
address_zip: 02139

# Build settings
markdown: kramdown

# CSS settings
sass:
    style: compressed
